; Auto-generated. Do not edit!


(cl:in-package tug_ros_examples-msg)


;//! \htmlinclude FactorialFeedback.msg.html

(cl:defclass <FactorialFeedback> (roslisp-msg-protocol:ros-message)
  ((iteration
    :reader iteration
    :initarg :iteration
    :type cl:integer
    :initform 0))
)

(cl:defclass FactorialFeedback (<FactorialFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FactorialFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FactorialFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tug_ros_examples-msg:<FactorialFeedback> is deprecated: use tug_ros_examples-msg:FactorialFeedback instead.")))

(cl:ensure-generic-function 'iteration-val :lambda-list '(m))
(cl:defmethod iteration-val ((m <FactorialFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tug_ros_examples-msg:iteration-val is deprecated.  Use tug_ros_examples-msg:iteration instead.")
  (iteration m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FactorialFeedback>) ostream)
  "Serializes a message object of type '<FactorialFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'iteration)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FactorialFeedback>) istream)
  "Deserializes a message object of type '<FactorialFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'iteration) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FactorialFeedback>)))
  "Returns string type for a message object of type '<FactorialFeedback>"
  "tug_ros_examples/FactorialFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FactorialFeedback)))
  "Returns string type for a message object of type 'FactorialFeedback"
  "tug_ros_examples/FactorialFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FactorialFeedback>)))
  "Returns md5sum for a message object of type '<FactorialFeedback>"
  "d01a95a2075b56b72c44d80791c1039b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FactorialFeedback)))
  "Returns md5sum for a message object of type 'FactorialFeedback"
  "d01a95a2075b56b72c44d80791c1039b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FactorialFeedback>)))
  "Returns full string definition for message of type '<FactorialFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 iteration~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FactorialFeedback)))
  "Returns full string definition for message of type 'FactorialFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 iteration~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FactorialFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FactorialFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'FactorialFeedback
    (cl:cons ':iteration (iteration msg))
))
