; Auto-generated. Do not edit!


(cl:in-package tug_ros_examples-msg)


;//! \htmlinclude FactorialResult.msg.html

(cl:defclass <FactorialResult> (roslisp-msg-protocol:ros-message)
  ((factorial
    :reader factorial
    :initarg :factorial
    :type cl:integer
    :initform 0))
)

(cl:defclass FactorialResult (<FactorialResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FactorialResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FactorialResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tug_ros_examples-msg:<FactorialResult> is deprecated: use tug_ros_examples-msg:FactorialResult instead.")))

(cl:ensure-generic-function 'factorial-val :lambda-list '(m))
(cl:defmethod factorial-val ((m <FactorialResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tug_ros_examples-msg:factorial-val is deprecated.  Use tug_ros_examples-msg:factorial instead.")
  (factorial m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FactorialResult>) ostream)
  "Serializes a message object of type '<FactorialResult>"
  (cl:let* ((signed (cl:slot-value msg 'factorial)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FactorialResult>) istream)
  "Deserializes a message object of type '<FactorialResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'factorial) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FactorialResult>)))
  "Returns string type for a message object of type '<FactorialResult>"
  "tug_ros_examples/FactorialResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FactorialResult)))
  "Returns string type for a message object of type 'FactorialResult"
  "tug_ros_examples/FactorialResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FactorialResult>)))
  "Returns md5sum for a message object of type '<FactorialResult>"
  "2faed1f7e343c27e6be21b681c21d44e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FactorialResult)))
  "Returns md5sum for a message object of type 'FactorialResult"
  "2faed1f7e343c27e6be21b681c21d44e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FactorialResult>)))
  "Returns full string definition for message of type '<FactorialResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 factorial~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FactorialResult)))
  "Returns full string definition for message of type 'FactorialResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 factorial~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FactorialResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FactorialResult>))
  "Converts a ROS message object to a list"
  (cl:list 'FactorialResult
    (cl:cons ':factorial (factorial msg))
))
