; Auto-generated. Do not edit!


(cl:in-package tug_ros_examples-msg)


;//! \htmlinclude FactorialGoal.msg.html

(cl:defclass <FactorialGoal> (roslisp-msg-protocol:ros-message)
  ((number
    :reader number
    :initarg :number
    :type cl:integer
    :initform 0))
)

(cl:defclass FactorialGoal (<FactorialGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FactorialGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FactorialGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tug_ros_examples-msg:<FactorialGoal> is deprecated: use tug_ros_examples-msg:FactorialGoal instead.")))

(cl:ensure-generic-function 'number-val :lambda-list '(m))
(cl:defmethod number-val ((m <FactorialGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tug_ros_examples-msg:number-val is deprecated.  Use tug_ros_examples-msg:number instead.")
  (number m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FactorialGoal>) ostream)
  "Serializes a message object of type '<FactorialGoal>"
  (cl:let* ((signed (cl:slot-value msg 'number)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FactorialGoal>) istream)
  "Deserializes a message object of type '<FactorialGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'number) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FactorialGoal>)))
  "Returns string type for a message object of type '<FactorialGoal>"
  "tug_ros_examples/FactorialGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FactorialGoal)))
  "Returns string type for a message object of type 'FactorialGoal"
  "tug_ros_examples/FactorialGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FactorialGoal>)))
  "Returns md5sum for a message object of type '<FactorialGoal>"
  "2474488a3908093ec1307bdd5b35815e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FactorialGoal)))
  "Returns md5sum for a message object of type 'FactorialGoal"
  "2474488a3908093ec1307bdd5b35815e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FactorialGoal>)))
  "Returns full string definition for message of type '<FactorialGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FactorialGoal)))
  "Returns full string definition for message of type 'FactorialGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FactorialGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FactorialGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'FactorialGoal
    (cl:cons ':number (number msg))
))
