// Generated by gencpp from file tug_mobile_robots/CallMovement.msg
// DO NOT EDIT!


#ifndef TUG_MOBILE_ROBOTS_MESSAGE_CALLMOVEMENT_H
#define TUG_MOBILE_ROBOTS_MESSAGE_CALLMOVEMENT_H

#include <ros/service_traits.h>


#include <tug_mobile_robots/CallMovementRequest.h>
#include <tug_mobile_robots/CallMovementResponse.h>


namespace tug_mobile_robots
{

struct CallMovement
{

typedef CallMovementRequest Request;
typedef CallMovementResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CallMovement
} // namespace tug_mobile_robots


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tug_mobile_robots::CallMovement > {
  static const char* value()
  {
    return "a6594aca386314dea20490c6d462aabc";
  }

  static const char* value(const ::tug_mobile_robots::CallMovement&) { return value(); }
};

template<>
struct DataType< ::tug_mobile_robots::CallMovement > {
  static const char* value()
  {
    return "tug_mobile_robots/CallMovement";
  }

  static const char* value(const ::tug_mobile_robots::CallMovement&) { return value(); }
};


// service_traits::MD5Sum< ::tug_mobile_robots::CallMovementRequest> should match 
// service_traits::MD5Sum< ::tug_mobile_robots::CallMovement > 
template<>
struct MD5Sum< ::tug_mobile_robots::CallMovementRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tug_mobile_robots::CallMovement >::value();
  }
  static const char* value(const ::tug_mobile_robots::CallMovementRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tug_mobile_robots::CallMovementRequest> should match 
// service_traits::DataType< ::tug_mobile_robots::CallMovement > 
template<>
struct DataType< ::tug_mobile_robots::CallMovementRequest>
{
  static const char* value()
  {
    return DataType< ::tug_mobile_robots::CallMovement >::value();
  }
  static const char* value(const ::tug_mobile_robots::CallMovementRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tug_mobile_robots::CallMovementResponse> should match 
// service_traits::MD5Sum< ::tug_mobile_robots::CallMovement > 
template<>
struct MD5Sum< ::tug_mobile_robots::CallMovementResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tug_mobile_robots::CallMovement >::value();
  }
  static const char* value(const ::tug_mobile_robots::CallMovementResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tug_mobile_robots::CallMovementResponse> should match 
// service_traits::DataType< ::tug_mobile_robots::CallMovement > 
template<>
struct DataType< ::tug_mobile_robots::CallMovementResponse>
{
  static const char* value()
  {
    return DataType< ::tug_mobile_robots::CallMovement >::value();
  }
  static const char* value(const ::tug_mobile_robots::CallMovementResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUG_MOBILE_ROBOTS_MESSAGE_CALLMOVEMENT_H
