// Generated by gencpp from file tug_mobile_robots/CallMovementResponse.msg
// DO NOT EDIT!


#ifndef TUG_MOBILE_ROBOTS_MESSAGE_CALLMOVEMENTRESPONSE_H
#define TUG_MOBILE_ROBOTS_MESSAGE_CALLMOVEMENTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tug_mobile_robots
{
template <class ContainerAllocator>
struct CallMovementResponse_
{
  typedef CallMovementResponse_<ContainerAllocator> Type;

  CallMovementResponse_()
    {
    }
  CallMovementResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::tug_mobile_robots::CallMovementResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tug_mobile_robots::CallMovementResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CallMovementResponse_

typedef ::tug_mobile_robots::CallMovementResponse_<std::allocator<void> > CallMovementResponse;

typedef boost::shared_ptr< ::tug_mobile_robots::CallMovementResponse > CallMovementResponsePtr;
typedef boost::shared_ptr< ::tug_mobile_robots::CallMovementResponse const> CallMovementResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tug_mobile_robots::CallMovementResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tug_mobile_robots::CallMovementResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tug_mobile_robots

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tug_mobile_robots::CallMovementResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tug_mobile_robots::CallMovementResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_mobile_robots::CallMovementResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_mobile_robots::CallMovementResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_mobile_robots::CallMovementResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_mobile_robots::CallMovementResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tug_mobile_robots::CallMovementResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::tug_mobile_robots::CallMovementResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::tug_mobile_robots::CallMovementResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tug_mobile_robots/CallMovementResponse";
  }

  static const char* value(const ::tug_mobile_robots::CallMovementResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tug_mobile_robots::CallMovementResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
;
  }

  static const char* value(const ::tug_mobile_robots::CallMovementResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tug_mobile_robots::CallMovementResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CallMovementResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tug_mobile_robots::CallMovementResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::tug_mobile_robots::CallMovementResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TUG_MOBILE_ROBOTS_MESSAGE_CALLMOVEMENTRESPONSE_H
