// Generated by gencpp from file tug_mobile_robots/CallMovementRequest.msg
// DO NOT EDIT!


#ifndef TUG_MOBILE_ROBOTS_MESSAGE_CALLMOVEMENTREQUEST_H
#define TUG_MOBILE_ROBOTS_MESSAGE_CALLMOVEMENTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tug_mobile_robots
{
template <class ContainerAllocator>
struct CallMovementRequest_
{
  typedef CallMovementRequest_<ContainerAllocator> Type;

  CallMovementRequest_()
    : mode(0)  {
    }
  CallMovementRequest_(const ContainerAllocator& _alloc)
    : mode(0)  {
  (void)_alloc;
    }



   typedef int32_t _mode_type;
  _mode_type mode;



  enum {
    POSITION_MODE = 0,
    VELOCITY_MODE = 1,
    WHEEL_MODE = 2,
    ACKERMANN_MODE = 3,
  };


  typedef boost::shared_ptr< ::tug_mobile_robots::CallMovementRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tug_mobile_robots::CallMovementRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CallMovementRequest_

typedef ::tug_mobile_robots::CallMovementRequest_<std::allocator<void> > CallMovementRequest;

typedef boost::shared_ptr< ::tug_mobile_robots::CallMovementRequest > CallMovementRequestPtr;
typedef boost::shared_ptr< ::tug_mobile_robots::CallMovementRequest const> CallMovementRequestConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tug_mobile_robots::CallMovementRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tug_mobile_robots::CallMovementRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tug_mobile_robots

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tug_mobile_robots::CallMovementRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tug_mobile_robots::CallMovementRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_mobile_robots::CallMovementRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_mobile_robots::CallMovementRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_mobile_robots::CallMovementRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_mobile_robots::CallMovementRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tug_mobile_robots::CallMovementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a6594aca386314dea20490c6d462aabc";
  }

  static const char* value(const ::tug_mobile_robots::CallMovementRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa6594aca386314deULL;
  static const uint64_t static_value2 = 0xa20490c6d462aabcULL;
};

template<class ContainerAllocator>
struct DataType< ::tug_mobile_robots::CallMovementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tug_mobile_robots/CallMovementRequest";
  }

  static const char* value(const ::tug_mobile_robots::CallMovementRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tug_mobile_robots::CallMovementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 POSITION_MODE = 0\n"
"int32 VELOCITY_MODE = 1\n"
"int32 WHEEL_MODE = 2\n"
"int32 ACKERMANN_MODE=3\n"
"\n"
"int32 mode\n"
;
  }

  static const char* value(const ::tug_mobile_robots::CallMovementRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tug_mobile_robots::CallMovementRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CallMovementRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tug_mobile_robots::CallMovementRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tug_mobile_robots::CallMovementRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUG_MOBILE_ROBOTS_MESSAGE_CALLMOVEMENTREQUEST_H
