// Generated by gencpp from file tug_stage_ros/AckermannCmd.msg
// DO NOT EDIT!


#ifndef TUG_STAGE_ROS_MESSAGE_ACKERMANNCMD_H
#define TUG_STAGE_ROS_MESSAGE_ACKERMANNCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tug_stage_ros
{
template <class ContainerAllocator>
struct AckermannCmd_
{
  typedef AckermannCmd_<ContainerAllocator> Type;

  AckermannCmd_()
    : velocity(0.0)
    , steering(0.0)  {
    }
  AckermannCmd_(const ContainerAllocator& _alloc)
    : velocity(0.0)
    , steering(0.0)  {
  (void)_alloc;
    }



   typedef double _velocity_type;
  _velocity_type velocity;

   typedef double _steering_type;
  _steering_type steering;





  typedef boost::shared_ptr< ::tug_stage_ros::AckermannCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tug_stage_ros::AckermannCmd_<ContainerAllocator> const> ConstPtr;

}; // struct AckermannCmd_

typedef ::tug_stage_ros::AckermannCmd_<std::allocator<void> > AckermannCmd;

typedef boost::shared_ptr< ::tug_stage_ros::AckermannCmd > AckermannCmdPtr;
typedef boost::shared_ptr< ::tug_stage_ros::AckermannCmd const> AckermannCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tug_stage_ros::AckermannCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tug_stage_ros::AckermannCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tug_stage_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'tug_stage_ros': ['/home/robotics/catkin_ws/src/RoboticsUE/tug_stage_ros/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tug_stage_ros::AckermannCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tug_stage_ros::AckermannCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_stage_ros::AckermannCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_stage_ros::AckermannCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_stage_ros::AckermannCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_stage_ros::AckermannCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tug_stage_ros::AckermannCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2cccf116fd404cf82580c85a4b8c480d";
  }

  static const char* value(const ::tug_stage_ros::AckermannCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2cccf116fd404cf8ULL;
  static const uint64_t static_value2 = 0x2580c85a4b8c480dULL;
};

template<class ContainerAllocator>
struct DataType< ::tug_stage_ros::AckermannCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tug_stage_ros/AckermannCmd";
  }

  static const char* value(const ::tug_stage_ros::AckermannCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tug_stage_ros::AckermannCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Ackermann command\n"
"float64 velocity\n"
"float64 steering\n"
;
  }

  static const char* value(const ::tug_stage_ros::AckermannCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tug_stage_ros::AckermannCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
      stream.next(m.steering);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AckermannCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tug_stage_ros::AckermannCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tug_stage_ros::AckermannCmd_<ContainerAllocator>& v)
  {
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    s << indent << "steering: ";
    Printer<double>::stream(s, indent + "  ", v.steering);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUG_STAGE_ROS_MESSAGE_ACKERMANNCMD_H
