// Generated by gencpp from file tug_stage_ros/Fiducial.msg
// DO NOT EDIT!


#ifndef TUG_STAGE_ROS_MESSAGE_FIDUCIAL_H
#define TUG_STAGE_ROS_MESSAGE_FIDUCIAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tug_stage_ros
{
template <class ContainerAllocator>
struct Fiducial_
{
  typedef Fiducial_<ContainerAllocator> Type;

  Fiducial_()
    : range(0.0)
    , bearing(0.0)
    , type()
    , value(0.0)
    , id(0)  {
    }
  Fiducial_(const ContainerAllocator& _alloc)
    : range(0.0)
    , bearing(0.0)
    , type(_alloc)
    , value(0.0)
    , id(0)  {
  (void)_alloc;
    }



   typedef double _range_type;
  _range_type range;

   typedef double _bearing_type;
  _bearing_type bearing;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef double _value_type;
  _value_type value;

   typedef int64_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::tug_stage_ros::Fiducial_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tug_stage_ros::Fiducial_<ContainerAllocator> const> ConstPtr;

}; // struct Fiducial_

typedef ::tug_stage_ros::Fiducial_<std::allocator<void> > Fiducial;

typedef boost::shared_ptr< ::tug_stage_ros::Fiducial > FiducialPtr;
typedef boost::shared_ptr< ::tug_stage_ros::Fiducial const> FiducialConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tug_stage_ros::Fiducial_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tug_stage_ros::Fiducial_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tug_stage_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'tug_stage_ros': ['/home/robotics/catkin_ws/src/RoboticsUE/tug_stage_ros/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tug_stage_ros::Fiducial_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tug_stage_ros::Fiducial_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_stage_ros::Fiducial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_stage_ros::Fiducial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_stage_ros::Fiducial_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_stage_ros::Fiducial_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tug_stage_ros::Fiducial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "577001d6ebc2243eaa5af824faac55ef";
  }

  static const char* value(const ::tug_stage_ros::Fiducial_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x577001d6ebc2243eULL;
  static const uint64_t static_value2 = 0xaa5af824faac55efULL;
};

template<class ContainerAllocator>
struct DataType< ::tug_stage_ros::Fiducial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tug_stage_ros/Fiducial";
  }

  static const char* value(const ::tug_stage_ros::Fiducial_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tug_stage_ros::Fiducial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# beacon observation\n"
"float64 range\n"
"float64 bearing\n"
"string type\n"
"float64 value\n"
"int64 id\n"
;
  }

  static const char* value(const ::tug_stage_ros::Fiducial_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tug_stage_ros::Fiducial_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.range);
      stream.next(m.bearing);
      stream.next(m.type);
      stream.next(m.value);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Fiducial_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tug_stage_ros::Fiducial_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tug_stage_ros::Fiducial_<ContainerAllocator>& v)
  {
    s << indent << "range: ";
    Printer<double>::stream(s, indent + "  ", v.range);
    s << indent << "bearing: ";
    Printer<double>::stream(s, indent + "  ", v.bearing);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "value: ";
    Printer<double>::stream(s, indent + "  ", v.value);
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUG_STAGE_ROS_MESSAGE_FIDUCIAL_H
