// Generated by gencpp from file tug_stage_ros/SetRobotPose.msg
// DO NOT EDIT!


#ifndef TUG_STAGE_ROS_MESSAGE_SETROBOTPOSE_H
#define TUG_STAGE_ROS_MESSAGE_SETROBOTPOSE_H

#include <ros/service_traits.h>


#include <tug_stage_ros/SetRobotPoseRequest.h>
#include <tug_stage_ros/SetRobotPoseResponse.h>


namespace tug_stage_ros
{

struct SetRobotPose
{

typedef SetRobotPoseRequest Request;
typedef SetRobotPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRobotPose
} // namespace tug_stage_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tug_stage_ros::SetRobotPose > {
  static const char* value()
  {
    return "b71344c0ba01936756dc45bcd89ef437";
  }

  static const char* value(const ::tug_stage_ros::SetRobotPose&) { return value(); }
};

template<>
struct DataType< ::tug_stage_ros::SetRobotPose > {
  static const char* value()
  {
    return "tug_stage_ros/SetRobotPose";
  }

  static const char* value(const ::tug_stage_ros::SetRobotPose&) { return value(); }
};


// service_traits::MD5Sum< ::tug_stage_ros::SetRobotPoseRequest> should match 
// service_traits::MD5Sum< ::tug_stage_ros::SetRobotPose > 
template<>
struct MD5Sum< ::tug_stage_ros::SetRobotPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tug_stage_ros::SetRobotPose >::value();
  }
  static const char* value(const ::tug_stage_ros::SetRobotPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tug_stage_ros::SetRobotPoseRequest> should match 
// service_traits::DataType< ::tug_stage_ros::SetRobotPose > 
template<>
struct DataType< ::tug_stage_ros::SetRobotPoseRequest>
{
  static const char* value()
  {
    return DataType< ::tug_stage_ros::SetRobotPose >::value();
  }
  static const char* value(const ::tug_stage_ros::SetRobotPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tug_stage_ros::SetRobotPoseResponse> should match 
// service_traits::MD5Sum< ::tug_stage_ros::SetRobotPose > 
template<>
struct MD5Sum< ::tug_stage_ros::SetRobotPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tug_stage_ros::SetRobotPose >::value();
  }
  static const char* value(const ::tug_stage_ros::SetRobotPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tug_stage_ros::SetRobotPoseResponse> should match 
// service_traits::DataType< ::tug_stage_ros::SetRobotPose > 
template<>
struct DataType< ::tug_stage_ros::SetRobotPoseResponse>
{
  static const char* value()
  {
    return DataType< ::tug_stage_ros::SetRobotPose >::value();
  }
  static const char* value(const ::tug_stage_ros::SetRobotPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUG_STAGE_ROS_MESSAGE_SETROBOTPOSE_H
