// Generated by gencpp from file tug_ros_examples/FactorialGoal.msg
// DO NOT EDIT!


#ifndef TUG_ROS_EXAMPLES_MESSAGE_FACTORIALGOAL_H
#define TUG_ROS_EXAMPLES_MESSAGE_FACTORIALGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tug_ros_examples
{
template <class ContainerAllocator>
struct FactorialGoal_
{
  typedef FactorialGoal_<ContainerAllocator> Type;

  FactorialGoal_()
    : number(0)  {
    }
  FactorialGoal_(const ContainerAllocator& _alloc)
    : number(0)  {
  (void)_alloc;
    }



   typedef int32_t _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::tug_ros_examples::FactorialGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tug_ros_examples::FactorialGoal_<ContainerAllocator> const> ConstPtr;

}; // struct FactorialGoal_

typedef ::tug_ros_examples::FactorialGoal_<std::allocator<void> > FactorialGoal;

typedef boost::shared_ptr< ::tug_ros_examples::FactorialGoal > FactorialGoalPtr;
typedef boost::shared_ptr< ::tug_ros_examples::FactorialGoal const> FactorialGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tug_ros_examples::FactorialGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tug_ros_examples::FactorialGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tug_ros_examples

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'tug_ros_examples': ['/home/robotics/catkin_ws/devel/share/tug_ros_examples/msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tug_ros_examples::FactorialGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tug_ros_examples::FactorialGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_ros_examples::FactorialGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_ros_examples::FactorialGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_ros_examples::FactorialGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_ros_examples::FactorialGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tug_ros_examples::FactorialGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2474488a3908093ec1307bdd5b35815e";
  }

  static const char* value(const ::tug_ros_examples::FactorialGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2474488a3908093eULL;
  static const uint64_t static_value2 = 0xc1307bdd5b35815eULL;
};

template<class ContainerAllocator>
struct DataType< ::tug_ros_examples::FactorialGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tug_ros_examples/FactorialGoal";
  }

  static const char* value(const ::tug_ros_examples::FactorialGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tug_ros_examples::FactorialGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"int32 number\n"
;
  }

  static const char* value(const ::tug_ros_examples::FactorialGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tug_ros_examples::FactorialGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FactorialGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tug_ros_examples::FactorialGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tug_ros_examples::FactorialGoal_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUG_ROS_EXAMPLES_MESSAGE_FACTORIALGOAL_H
