// Generated by gencpp from file tug_ros_examples/FactorialActionGoal.msg
// DO NOT EDIT!


#ifndef TUG_ROS_EXAMPLES_MESSAGE_FACTORIALACTIONGOAL_H
#define TUG_ROS_EXAMPLES_MESSAGE_FACTORIALACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <tug_ros_examples/FactorialGoal.h>

namespace tug_ros_examples
{
template <class ContainerAllocator>
struct FactorialActionGoal_
{
  typedef FactorialActionGoal_<ContainerAllocator> Type;

  FactorialActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  FactorialActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::tug_ros_examples::FactorialGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::tug_ros_examples::FactorialActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tug_ros_examples::FactorialActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct FactorialActionGoal_

typedef ::tug_ros_examples::FactorialActionGoal_<std::allocator<void> > FactorialActionGoal;

typedef boost::shared_ptr< ::tug_ros_examples::FactorialActionGoal > FactorialActionGoalPtr;
typedef boost::shared_ptr< ::tug_ros_examples::FactorialActionGoal const> FactorialActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tug_ros_examples::FactorialActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tug_ros_examples::FactorialActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tug_ros_examples

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'tug_ros_examples': ['/home/robotics/catkin_ws/devel/share/tug_ros_examples/msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tug_ros_examples::FactorialActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tug_ros_examples::FactorialActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_ros_examples::FactorialActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_ros_examples::FactorialActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_ros_examples::FactorialActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_ros_examples::FactorialActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tug_ros_examples::FactorialActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae26cdf3239560efb8e3cd667b757d26";
  }

  static const char* value(const ::tug_ros_examples::FactorialActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae26cdf3239560efULL;
  static const uint64_t static_value2 = 0xb8e3cd667b757d26ULL;
};

template<class ContainerAllocator>
struct DataType< ::tug_ros_examples::FactorialActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tug_ros_examples/FactorialActionGoal";
  }

  static const char* value(const ::tug_ros_examples::FactorialActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tug_ros_examples::FactorialActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"FactorialGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: tug_ros_examples/FactorialGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"int32 number\n"
;
  }

  static const char* value(const ::tug_ros_examples::FactorialActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tug_ros_examples::FactorialActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FactorialActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tug_ros_examples::FactorialActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tug_ros_examples::FactorialActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::tug_ros_examples::FactorialGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUG_ROS_EXAMPLES_MESSAGE_FACTORIALACTIONGOAL_H
